# Generated by Django 4.2.8 on 2024-01-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TeamMembers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Last Name"),
                ),
                (
                    "phone",
                    models.CharField(max_length=100, verbose_name="Phone Number"),
                ),
                ("email", models.CharField(max_length=100, verbose_name="Email")),
                ("offer", models.IntegerField(default=0)),
                ("addendum", models.IntegerField(default=0)),
                ("listing", models.IntegerField(default=0)),
                ("mls_attachments", models.IntegerField(default=0)),
                ("mls_search", models.IntegerField(default=0)),
                ("dotloop", models.IntegerField(default=0)),
            ],
        ),
    ]
