# Generated by Django 4.2.8 on 2024-01-08 01:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TeamMembers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teammembers",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="teammembers",
            name="last_name",
        ),
        migrations.AddField(
            model_name="teammembers",
            name="name",
            field=models.CharField(
                default=" ", max_length=100, verbose_name="Agent's Name"
            ),
            preserve_default=False,
        ),
    ]
