# Generated by Django 4.2.8 on 2024-01-08 01:06

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("Tickets", "0002_createaddendum_createlisting_createoffer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="createaddendum",
            name="credit_amount",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                currency_choices=[("USD", "USD")],
                decimal_places=2,
                default_currency="USD",
                max_digits=10,
                null=True,
                verbose_name="Credit Amount",
            ),
        ),
        migrations.AlterField(
            model_name="createaddendum",
            name="credit_amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("USD", "USD")],
                default="USD",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="createaddendum",
            name="four_points",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Which items from the 4-point Inspection Report are to be added?",
            ),
        ),
    ]
