# Generated by Django 4.2.8 on 2024-01-09 01:22

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("TeamMembers", "0002_remove_teammembers_first_name_and_more"),
        ("Tickets", "0003_alter_createaddendum_credit_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="createaddendum",
            name="credit_amount",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                currency_choices=[("USD", "USD")],
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Credit Amount",
            ),
        ),
        migrations.AlterField(
            model_name="createaddendum",
            name="credit_amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("USD", "USD")],
                default=None,
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="CreateSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "search",
                    models.TextField(
                        blank=True, null=True, verbose_name="Criteria of search"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Lead’s name shown on FUB",
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="TeamMembers.teammembers",
                        verbose_name="Agent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CreateMLSsheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(max_length=100, verbose_name="Property Address"),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Lead’s name shown on FUB",
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "attachment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MLS", "MLS Customer Sheet"),
                            ("Attachments", "Attachments"),
                            ("Both", "MLS Customer Sheet & Attachments"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Which attachment",
                    ),
                ),
                (
                    "additional",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Additional request information",
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="TeamMembers.teammembers",
                        verbose_name="Agent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CreateDotloop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(max_length=100, verbose_name="Property Address"),
                ),
                (
                    "inquiry",
                    models.CharField(
                        choices=[
                            ("Commission split", "Commission split"),
                            ("DA not received", "DA not received"),
                            ("Compliance docs", "Compliance docs"),
                        ],
                        max_length=20,
                        verbose_name="Inquiry?",
                    ),
                ),
                (
                    "additional",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Additional details (Explain)",
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="TeamMembers.teammembers",
                        verbose_name="Agent",
                    ),
                ),
            ],
        ),
    ]
