# Generated by Django 4.2.8 on 2024-01-09 01:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Tickets", "0005_alter_createaddendum_add_remove_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="createaddendum",
            name="add_remove",
            field=models.CharField(
                choices=[("Add", "Add"), ("Remove", "Remove")],
                default="",
                max_length=20,
                verbose_name="Add/Remove",
            ),
        ),
    ]
