# Generated by Django 4.2.8 on 2024-01-09 01:34

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("Tickets", "0008_alter_createaddendum_add_remove_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="createaddendum",
            name="credit_amount",
            field=djmoney.models.fields.MoneyField(
                currency_choices=[("USD", "USD")],
                decimal_places=2,
                max_digits=10,
                verbose_name="Credit Amount",
            ),
        ),
        migrations.AlterField(
            model_name="createaddendum",
            name="credit_amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("USD", "USD")], default=None, editable=False, max_length=3
            ),
        ),
    ]
