# Generated by Django 4.2.8 on 2024-01-09 01:49

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("Tickets", "0010_alter_createaddendum_additional_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="createaddendum",
            name="additional",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Additional Terms"
            ),
        ),
        migrations.AlterField(
            model_name="createaddendum",
            name="credit_amount",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                currency_choices=[("USD", "USD")],
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Credit Amount",
            ),
        ),
    ]
