# Generated by Django 4.2.8 on 2024-01-09 01:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Tickets", "0011_alter_createaddendum_additional_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="createaddendum",
            name="inspection_report",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=3,
                null=True,
                verbose_name="Email the inspection reports to admin@militaryvetteam and fischerclosing@gmail.com",
            ),
        ),
    ]
