# Generated by Django 4.2.8 on 2024-01-09 02:05

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("Tickets", "0012_alter_createaddendum_inspection_report"),
    ]

    operations = [
        migrations.RenameField(
            model_name="createaddendum",
            old_name="credit_amount",
            new_name="credit_buyer_seller",
        ),
        migrations.RenameField(
            model_name="createaddendum",
            old_name="credit_amount_currency",
            new_name="credit_buyer_seller_currency",
        ),
        migrations.AddField(
            model_name="createaddendum",
            name="credit_repair",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                currency_choices=[("USD", "USD")],
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Credit Amount",
            ),
        ),
        migrations.AddField(
            model_name="createaddendum",
            name="credit_repair_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("USD", "USD")],
                default=None,
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="createaddendum",
            name="additional",
            field=models.TextField(
                blank=True, null=True, verbose_name="Additional Terms"
            ),
        ),
    ]
