# Generated by Django 4.2.8 on 2024-01-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "Tickets",
            "0013_rename_credit_amount_createaddendum_credit_buyer_seller_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="createaddendum",
            name="buyer_seller_2",
            field=models.CharField(
                blank=True,
                choices=[("Buyer", "Buyer"), ("Seller", "Seller")],
                max_length=20,
                null=True,
                verbose_name="Buyer/Seller",
            ),
        ),
    ]
