# Generated by Django 4.2.8 on 2024-01-09 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Tickets", "0016_createoffer_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="createaddendum",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="createdotloop",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 1, 9, 19, 59, 34, 428278, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="createlisting",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 1, 9, 19, 59, 49, 725169, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="createmlssheet",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 1, 9, 19, 59, 58, 701748, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="createsearch",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 1, 9, 20, 0, 2, 820989, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
