# Generated by Django 4.2.8 on 2024-01-10 19:54

import datetime
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("Tickets", "0017_createaddendum_created_createdotloop_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="createlisting",
            name="option",
            field=models.CharField(
                choices=[
                    ("Listing Agreement", "Listing Agreement"),
                    ("ShowingTime+ Photoshoot", "ShowingTime+ Photoshoot"),
                    ("Highnote/CMA", "Highnote/CMA"),
                ],
                default=datetime.datetime(
                    2024, 1, 10, 19, 53, 48, 695543, tzinfo=datetime.timezone.utc
                ),
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="createlisting",
            name="broker_fee",
            field=djmoney.models.fields.MoneyField(
                currency_choices=[("USD", "US Dollar")],
                decimal_places=2,
                max_digits=6,
                verbose_name="Broker fee (if $0.00 it will be charged to the Listing Agent by LPT)",
            ),
        ),
        migrations.AlterField(
            model_name="createlisting",
            name="broker_fee_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("USD", "US Dollar")],
                default=None,
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="createlisting",
            name="cancellation_fee",
            field=djmoney.models.fields.MoneyField(
                currency_choices=[("USD", "US Dollar")],
                decimal_places=2,
                max_digits=6,
                verbose_name="Cancellation Fee",
            ),
        ),
        migrations.AlterField(
            model_name="createlisting",
            name="cancellation_fee_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("USD", "US Dollar")],
                default=None,
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="createlisting",
            name="listing_price",
            field=djmoney.models.fields.MoneyField(
                currency_choices=[("USD", "US Dollar")],
                decimal_places=2,
                max_digits=20,
                verbose_name="Listing Price",
            ),
        ),
        migrations.AlterField(
            model_name="createlisting",
            name="listing_price_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("USD", "US Dollar")],
                default=None,
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="createlisting",
            name="mls_fee",
            field=djmoney.models.fields.MoneyField(
                currency_choices=[("USD", "US Dollar")],
                decimal_places=2,
                max_digits=6,
                verbose_name="MLS Fee",
            ),
        ),
        migrations.AlterField(
            model_name="createlisting",
            name="mls_fee_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("USD", "US Dollar")],
                default=None,
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="createmlssheet",
            name="attachment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MLS Customer Sheet", "MLS Customer Sheet"),
                    ("Attachments", "Attachments"),
                    (
                        "MLS Customer Sheet & Attachments",
                        "MLS Customer Sheet & Attachments",
                    ),
                ],
                max_length=100,
                null=True,
                verbose_name="Which attachment",
            ),
        ),
        migrations.AlterField(
            model_name="createoffer",
            name="proof",
            field=models.BooleanField(
                default=0,
                verbose_name="Email the proof of funds or Pre-approval to admin@militaryvetteam and fischerclosing@gmail.com",
            ),
            preserve_default=False,
        ),
    ]
