# Generated by Django 4.2.8 on 2024-01-11 01:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "Tickets",
            "0018_createlisting_option_alter_createlisting_broker_fee_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="createaddendum",
            old_name="credit_buyer_seller",
            new_name="credit_amount",
        ),
        migrations.RenameField(
            model_name="createaddendum",
            old_name="credit_buyer_seller_currency",
            new_name="credit_amount_currency",
        ),
        migrations.RemoveField(
            model_name="createaddendum",
            name="buyer_seller_2",
        ),
        migrations.RemoveField(
            model_name="createaddendum",
            name="credit_repair",
        ),
        migrations.RemoveField(
            model_name="createaddendum",
            name="credit_repair_currency",
        ),
        migrations.AlterField(
            model_name="createdotloop",
            name="additional",
            field=models.TextField(
                blank=True, null=True, verbose_name="Additional details (Explain)"
            ),
        ),
    ]
