# Generated by Django 4.2.8 on 2024-01-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Tickets", "0020_alter_createaddendum_inspection_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="createaddendum",
            name="cancellation_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Client changed mind", "Client changed mind"),
                    ("Inspection Unsatisfactory", "Inspection Unsatisfactory"),
                    ("Finance fell through", "Finance fell through"),
                    ("Low Appraisal", "Low Appraisal"),
                    ("Other", "Other"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="createaddendum",
            name="disbursement",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Disbursement of Escrow Funds",
            ),
        ),
        migrations.AddField(
            model_name="createaddendum",
            name="other",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="In case you select 'other' please tell us the reason",
            ),
        ),
        migrations.AlterField(
            model_name="createaddendum",
            name="addendum",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Repair Addendum", "Repair Addendum"),
                    ("Closing Date Addendum", "Closing Date Addendum"),
                    (
                        "Credit By Seller/Buyer Addendum",
                        "Credit By Seller/Buyer Addendum",
                    ),
                    ("Add or Remove Signer", "Add or Remove Signer"),
                    ("Other Addendum", "Other Addendum"),
                    ("Release and Cancellation", "Release and Cancellation"),
                ],
                max_length=100,
                null=True,
                verbose_name="Addendum",
            ),
        ),
    ]
