# Generated by Django 4.2.8 on 2024-01-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Tickets", "0021_createaddendum_cancellation_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="createlisting",
            name="highnote",
            field=models.CharField(
                choices=[
                    ("Highnote", "Highnote"),
                    ("CMA", "CAM"),
                    ("Highnote & CMA", "Highnote & CMA"),
                ],
                default="null",
                max_length=100,
                verbose_name="Highnote/CMA",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="createlisting",
            name="option",
            field=models.CharField(
                choices=[
                    ("Listing Agreement", "Listing Agreement"),
                    ("ShowingTime+ Photoshoot", "ShowingTime+ Photoshoot"),
                    ("Highnote/CMA", "Highnote/CMA"),
                ],
                max_length=100,
                verbose_name="Request",
            ),
        ),
    ]
