# Generated by Django 4.2.8 on 2024-01-15 01:45

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("Tickets", "0022_createlisting_highnote_alter_createlisting_option"),
    ]

    operations = [
        migrations.AddField(
            model_name="createlisting",
            name="otheragent_commission",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Buyer's Agent Commission",
            ),
        ),
        migrations.AlterField(
            model_name="createlisting",
            name="appliances",
            field=models.TextField(
                blank=True, null=True, verbose_name="Appliances Included"
            ),
        ),
        migrations.AlterField(
            model_name="createlisting",
            name="bothsides_commission",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Listing Agent commission if he/she brings the buyer",
            ),
        ),
        migrations.AlterField(
            model_name="createlisting",
            name="broker_fee",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                currency_choices=[("USD", "US Dollar")],
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Broker fee (if $0.00 it will be charged to the Listing Agent by LPT)",
            ),
        ),
        migrations.AlterField(
            model_name="createlisting",
            name="broker_fee_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("USD", "US Dollar")],
                default=None,
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="createlisting",
            name="cancellation_fee",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                currency_choices=[("USD", "US Dollar")],
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Cancellation Fee",
            ),
        ),
        migrations.AlterField(
            model_name="createlisting",
            name="cancellation_fee_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("USD", "US Dollar")],
                default=None,
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="createlisting",
            name="highnote",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Highnote", "Highnote"),
                    ("CMA", "CAM"),
                    ("Highnote & CMA", "Highnote & CMA"),
                ],
                max_length=100,
                null=True,
                verbose_name="Highnote/CMA",
            ),
        ),
        migrations.AlterField(
            model_name="createlisting",
            name="listing_commission",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Listing Agent Commission",
            ),
        ),
        migrations.AlterField(
            model_name="createlisting",
            name="listing_date",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Listing Date (should be the same as the Live date)",
            ),
        ),
        migrations.AlterField(
            model_name="createlisting",
            name="listing_expiration",
            field=models.DateField(
                blank=True, null=True, verbose_name="Listing Expiration Date"
            ),
        ),
        migrations.AlterField(
            model_name="createlisting",
            name="listing_price",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                currency_choices=[("USD", "US Dollar")],
                decimal_places=2,
                max_digits=20,
                null=True,
                verbose_name="Listing Price",
            ),
        ),
        migrations.AlterField(
            model_name="createlisting",
            name="listing_price_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("USD", "US Dollar")],
                default=None,
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="createlisting",
            name="lockbox",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Use of Lockbox"
            ),
        ),
        migrations.AlterField(
            model_name="createlisting",
            name="mls_fee",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                currency_choices=[("USD", "US Dollar")],
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="MLS Fee",
            ),
        ),
        migrations.AlterField(
            model_name="createlisting",
            name="mls_fee_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("USD", "US Dollar")],
                default=None,
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="createlisting",
            name="ocupancy",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Property Ocupancy"
            ),
        ),
        migrations.AlterField(
            model_name="createlisting",
            name="option",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Listing Agreement", "Listing Agreement"),
                    ("ShowingTime+ Photoshoot", "ShowingTime+ Photoshoot"),
                    ("Highnote/CMA", "Highnote/CMA"),
                ],
                max_length=100,
                null=True,
                verbose_name="Request",
            ),
        ),
        migrations.AlterField(
            model_name="createlisting",
            name="seller_email",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Seller’s email addresses",
            ),
        ),
        migrations.AlterField(
            model_name="createlisting",
            name="seller_name",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Seller Legal Full Name",
            ),
        ),
    ]
