# Generated by Django 4.2.8 on 2024-01-16 01:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Tickets", "0023_createlisting_otheragent_commission_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="createlisting",
            name="highnote",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Highnote", "Highnote"),
                    ("CMA", "CMA"),
                    ("Highnote & CMA", "Highnote & CMA"),
                ],
                max_length=100,
                null=True,
                verbose_name="Highnote/CMA",
            ),
        ),
    ]
