# Generated by Django 4.2.8 on 2024-01-19 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Tickets", "0024_alter_createlisting_highnote"),
    ]

    operations = [
        migrations.AddField(
            model_name="createaddendum",
            name="completed",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="createaddendum",
            name="completed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="createdotloop",
            name="completed",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="createdotloop",
            name="completed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="createlisting",
            name="completed",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="createlisting",
            name="completed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="createmlssheet",
            name="completed",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="createmlssheet",
            name="completed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="createoffer",
            name="completed",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="createoffer",
            name="completed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="createsearch",
            name="completed",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="createsearch",
            name="completed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="createlisting",
            name="contact_info",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Person in charge's info",
            ),
        ),
    ]
