# Generated by Django 4.2.8 on 2024-05-13 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0025_createaddendum_completed_createaddendum_completed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createaddendum',
            name='inspection_report',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True, verbose_name='Email the inspection reports to admin@demoemail.com'),
        ),
        migrations.AlterField(
            model_name='createoffer',
            name='proof',
            field=models.BooleanField(verbose_name='Email the proof of funds or Pre-approval to admin@demoemail.com'),
        ),
    ]
